apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include all components
resources:
  - base/
  - redis/redis-deployment.yaml
  - kafka/kafka-strimzi.yaml
  - ingress/ingress.yaml

# Common labels applied to all resources
commonLabels:
  environment: production

